import type { ContentItem, Drama, Episode, TimelineEvent, PlatformConfig } from '../../types/index.ts';

// Real verified drama records for Dananeer Mobeen
export const SEED_DRAMAS: Drama[] = [
  {
    id: 'muhabbat-gumshuda-meri',
    title: 'Muhabbat Gumshuda Meri',
    slug: 'muhabbat-gumshuda-meri',
    year: 2023,
    character: 'Zobia (Zubia)',
    network: 'HUM TV',
    networkChannel: 'HUM TV Official',
    officialSource: 'https://www.hum.tv/dramas/muhabbat-gumshuda-meri/',
    totalEpisodes: 26,
    status: 'Completed',
    synopsis: 'A coming-of-age romantic drama centered on childhood neighbors Zobia and Saim whose youthful love faces intense societal opposition, family resistance, and harsh coming-of-age realities.',
    posterUrl: '/src/assets/images/drama_muhabbat_gumshuda_1791045494787.jpg',
    backdropUrl: '/src/assets/images/drama_muhabbat_gumshuda_1791045494787.jpg',
    director: 'Shahid Shafaat',
    writer: 'Rahat Jabeen',
    coStars: ['Khushhal Khan', 'Omair Rana', 'Farah Sadia', 'Ayesha Toor', 'Ali Tahir'],
    accolades: ['Lux Style Award for Best Emerging Talent in Television (Dananeer Mobeen)', 'Viewer Choice Drama of the Year (Nominee)'],
    officialPlaylistUrl: 'https://www.youtube.com/playlist?list=PLbV86997n4h6Uu_x-yQ5cZ5A3sHk6KxIu'
  },
  {
    id: 'sinf-e-aahan',
    title: 'Sinf-e-Aahan',
    slug: 'sinf-e-aahan',
    year: 2021,
    character: 'Syeda Sidra',
    network: 'ARY Digital',
    networkChannel: 'ARY Digital HD / ISPR',
    officialSource: 'https://arydigital.tv/dramas/sinf-e-aahan/',
    totalEpisodes: 24,
    status: 'Completed',
    synopsis: 'Produced by ISPR, Six Sigma Plus and Next Level Entertainment, this groundbreaking military drama chronicles the arduous journey of five young women from diverse cultural backgrounds undergoing training as cadets at the Pakistan Military Academy (PMA) Kakul.',
    posterUrl: '/src/assets/images/drama_sinf_e_aahan_1791045507812.jpg',
    backdropUrl: '/src/assets/images/drama_sinf_e_aahan_1791045507812.jpg',
    director: 'Nadeem Baig',
    writer: 'Umera Ahmed',
    coStars: ['Sajal Aly', 'Yumna Zaidi', 'Kubra Khan', 'Ramsha Khan', 'Syra Yousuf', 'Sheheryar Munawar', 'Usman Mukhtar'],
    accolades: ['Lux Style Awards - Best Television Play', 'Special Recognition by ISPR for Youth Motivation'],
    officialPlaylistUrl: 'https://www.youtube.com/playlist?list=PLbV86997n4h6SinfEAahanOfficial'
  },
  {
    id: 'very-filmy',
    title: 'Very Filmy',
    slug: 'very-filmy',
    year: 2024,
    character: 'Sania',
    network: 'HUM TV',
    networkChannel: 'HUM TV Official',
    officialSource: 'https://www.hum.tv/dramas/very-filmy/',
    totalEpisodes: 30,
    status: 'Completed',
    synopsis: 'A fast-paced Ramadan special romantic comedy filled with cinematic homages, lively banter, and family drama. Dananeer stars as Sania opposite Ameer Gilani in a vibrant story about family expectations and movie-style romance.',
    posterUrl: '/src/assets/images/drama_very_filmy_1791045519163.jpg',
    backdropUrl: '/src/assets/images/drama_very_filmy_1791045519163.jpg',
    director: 'Ali Hassan',
    writer: 'Muhammad Ahmed',
    coStars: ['Ameer Gilani', 'Bushra Ansari', 'Ali Safina', 'Mira Sethi', 'Umer Khan'],
    accolades: ['Top Rated Ramadan Comedy 2024', 'Digital Viewership Milestone Award'],
    officialPlaylistUrl: 'https://www.youtube.com/playlist?list=PLbV86997n4h6VeryFilmyOfficial'
  }
];

// Verified official episodes
export const SEED_EPISODES: Episode[] = [
  {
    id: 'ep-mgm-01',
    dramaId: 'muhabbat-gumshuda-meri',
    episodeNumber: 1,
    title: 'Muhabbat Gumshuda Meri - Episode 01',
    airDate: '2023-04-28',
    sourceUrl: 'https://www.youtube.com/watch?v=3gB9GjH8PzI',
    embedUrl: 'https://www.youtube.com/embed/3gB9GjH8PzI',
    thumbnailUrl: '/src/assets/images/drama_muhabbat_gumshuda_1791045494787.jpg',
    duration: '42:15',
    synopsis: 'Introduction of Zobia and Saim as next-door childhood companions in Islamabad navigating their teenage years, high school tensions, and budding affection.'
  },
  {
    id: 'ep-mgm-final',
    dramaId: 'muhabbat-gumshuda-meri',
    episodeNumber: 26,
    title: 'Muhabbat Gumshuda Meri - Last Episode',
    airDate: '2023-10-27',
    sourceUrl: 'https://www.youtube.com/watch?v=kY0wU9fQ2hA',
    embedUrl: 'https://www.youtube.com/embed/kY0wU9fQ2hA',
    thumbnailUrl: '/src/assets/images/drama_muhabbat_gumshuda_1791045494787.jpg',
    duration: '48:30',
    synopsis: 'The highly anticipated emotional finale where Zobia and Saim face the culmination of their difficult journeys, leading to an iconic resolution for viewers.'
  },
  {
    id: 'ep-sea-01',
    dramaId: 'sinf-e-aahan',
    episodeNumber: 1,
    title: 'Sinf-e-Aahan - Episode 01',
    airDate: '2021-11-27',
    sourceUrl: 'https://www.youtube.com/watch?v=qT5xV8zL4mU',
    embedUrl: 'https://www.youtube.com/embed/qT5xV8zL4mU',
    thumbnailUrl: '/src/assets/images/drama_sinf_e_aahan_1791045507812.jpg',
    duration: '45:10',
    synopsis: 'The journey begins: Syeda Sidra (Dananeer Mobeen), a lively and witty girl from a conservative family, dreams of joining the army despite comedic domestic hurdles.'
  },
  {
    id: 'ep-vf-01',
    dramaId: 'very-filmy',
    episodeNumber: 1,
    title: 'Very Filmy - Episode 01',
    airDate: '2024-03-12',
    sourceUrl: 'https://www.youtube.com/watch?v=mD4nK7pY3vE',
    embedUrl: 'https://www.youtube.com/embed/mD4nK7pY3vE',
    thumbnailUrl: '/src/assets/images/drama_very_filmy_1791045519163.jpg',
    duration: '38:40',
    synopsis: 'Sania is introduced with grand cinematic dreams and romantic ideals, clashing humorously with family traditions during Ramadan.'
  }
];

// Verified public content archive
export const SEED_CONTENT_ITEMS: ContentItem[] = [
  {
    id: 'cnt-pawri-orig',
    platform: 'Instagram',
    sourceUrl: 'https://www.instagram.com/p/CLABWqUha8j/',
    embedUrl: null,
    title: 'Pawri Hori Hai — The Original Viral Moment',
    description: 'The historic 5-second spontaneous video clip posted by Dananeer from Nathiagali that sparked a global cultural phenomenon across South Asia and beyond.',
    caption: 'Yeh hamari car hai, aur yeh hum hain, aur yeh hamari pawri hori hai!',
    publishedAt: '2021-02-06T14:30:00Z',
    discoveredAt: '2021-02-06T15:00:00Z',
    author: 'dananeerr',
    contentType: 'reel',
    thumbnailUrl: '/src/assets/images/dananeer_hero_cinematic_1791045480240.jpg',
    duration: '0:06',
    tags: ['viral', 'pawri-hori-hai', 'nathiagali', 'milestone'],
    dramaId: null,
    episodeNumber: null,
    people: ['Dananeer Mobeen'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { originalResolution: '1080x1920', verifiedAccount: true },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: false,
    canonicalId: null,
    duplicateCount: 3,
    crossPlatformSources: [
      { platform: 'YouTube', url: 'https://www.youtube.com/watch?v=6Q1q8E0rXvA', note: 'Trending re-upload and news report' },
      { platform: 'X', url: 'https://x.com/DananeerM/status/1358055628472930304', note: 'Official X announcement' }
    ]
  },
  {
    id: 'cnt-mgm-ost-hum',
    platform: 'YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=0k5G9Kx7kQo',
    embedUrl: 'https://www.youtube.com/embed/0k5G9Kx7kQo',
    title: 'Muhabbat Gumshuda Meri — Official OST (Full Song)',
    description: 'The official soundtrack of the hit HUM TV serial featuring poignant performances by Dananeer Mobeen and Khushhal Khan.',
    caption: 'HUM TV Drama Muhabbat Gumshuda Meri Official OST sung by Sibte Hassan & Nirmal Roy.',
    publishedAt: '2023-05-10T17:00:00Z',
    discoveredAt: '2023-05-10T18:00:00Z',
    author: 'HUM TV',
    contentType: 'video',
    thumbnailUrl: '/src/assets/images/drama_muhabbat_gumshuda_1791045494787.jpg',
    duration: '4:52',
    tags: ['drama', 'ost', 'muhabbat-gumshuda-meri', 'hum-tv', 'music'],
    dramaId: 'muhabbat-gumshuda-meri',
    episodeNumber: null,
    people: ['Dananeer Mobeen', 'Khushhal Khan'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { channelId: 'UC4JCksTqB3wLg6e2U7L9Zbg', officialBroadcast: true },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: true,
    crossPlatformSources: [
      { platform: 'Instagram', url: 'https://www.instagram.com/p/CsGBZl3o4nQ/', note: 'Official release teaser' }
    ]
  },
  {
    id: 'cnt-fuchsia-interview-2023',
    platform: 'Interview',
    sourceUrl: 'https://www.youtube.com/watch?v=8lM4bK2VpDw',
    embedUrl: 'https://www.youtube.com/embed/8lM4bK2VpDw',
    title: 'FUCHSIA Magazine In-Depth: Dananeer on Zobia & Life After Viral Fame',
    description: 'Dananeer Mobeen opens up to Rabia Mughni about the craft of acting, tackling emotionally intense breakdown scenes in Muhabbat Gumshuda Meri, and evolving into a serious performer.',
    caption: 'Exclusive Heart-to-Heart with Dananeer Mobeen | Gup Shup With Rabia | FUCHSIA Magazine',
    publishedAt: '2023-08-15T16:00:00Z',
    discoveredAt: '2023-08-15T17:30:00Z',
    author: 'FUCHSIA Magazine',
    contentType: 'interview',
    thumbnailUrl: '/src/assets/images/dananeer_hero_cinematic_1791045480240.jpg',
    duration: '45:18',
    tags: ['interview', 'fuchsia-magazine', 'acting-craft', 'rabia-mughni'],
    dramaId: 'muhabbat-gumshuda-meri',
    episodeNumber: null,
    people: ['Dananeer Mobeen', 'Rabia Mughni'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { verifiedJournalism: true, publication: 'FUCHSIA Magazine' },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: true
  },
  {
    id: 'cnt-something-haute-2024',
    platform: 'Interview',
    sourceUrl: 'https://www.youtube.com/watch?v=5Vz8L2aN9pM',
    embedUrl: 'https://www.youtube.com/embed/5Vz8L2aN9pM',
    title: 'Something Haute Haute Byte: Dananeer Mobeen on Very Filmy & Comedy Timing',
    description: 'Aamna Isani and Hassan Choudary interview Dananeer Mobeen about switching gears from serious tragedy in Muhabbat Gumshuda Meri to fast-paced comedy in Very Filmy.',
    caption: 'Dananeer Mobeen Candid Interview with Something Haute on Sania, Comedy and Ramadan Dramas',
    publishedAt: '2024-03-24T18:00:00Z',
    discoveredAt: '2024-03-24T19:00:00Z',
    author: 'Something Haute',
    contentType: 'interview',
    thumbnailUrl: '/src/assets/images/drama_very_filmy_1791045519163.jpg',
    duration: '32:44',
    tags: ['interview', 'something-haute', 'very-filmy', 'comedy', 'aamna-isani'],
    dramaId: 'very-filmy',
    episodeNumber: null,
    people: ['Dananeer Mobeen', 'Aamna Isani'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { verifiedJournalism: true, publication: 'Something Haute' },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: true
  },
  {
    id: 'cnt-lsa-2023-win',
    platform: 'Broadcast',
    sourceUrl: 'https://www.youtube.com/watch?v=7uV8hK3PnYq',
    embedUrl: 'https://www.youtube.com/embed/7uV8hK3PnYq',
    title: 'Lux Style Awards — Dananeer Mobeen Acceptance Speech & Red Carpet',
    description: 'Official coverage of Dananeer Mobeen winning the prestigious award for Best Emerging Talent in Television at the 22nd Lux Style Awards in Karachi.',
    caption: 'Dananeer Mobeen accepts Best Emerging Talent Award at Lux Style Awards ceremony.',
    publishedAt: '2023-10-07T21:00:00Z',
    discoveredAt: '2023-10-08T04:00:00Z',
    author: 'Lux Style Awards',
    contentType: 'appearance',
    thumbnailUrl: '/src/assets/images/dananeer_hero_cinematic_1791045480240.jpg',
    duration: '8:20',
    tags: ['awards', 'lux-style-awards', 'red-carpet', 'milestone', 'karachi'],
    dramaId: null,
    episodeNumber: null,
    people: ['Dananeer Mobeen'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { broadcastEvent: 'Lux Style Awards 2023' },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: true
  },
  {
    id: 'cnt-sea-bts-ispr',
    platform: 'YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=1bK8mP0xX9s',
    embedUrl: 'https://www.youtube.com/embed/1bK8mP0xX9s',
    title: 'Sinf-e-Aahan — Behind The Scenes & Cadet Training Diary',
    description: 'Official ISPR behind-the-scenes documentary showing Dananeer Mobeen and the ensemble cast experiencing real obstacle courses and drill sergeants at PMA Kakul.',
    caption: 'Cadet Syeda Sidra and cast share training experiences at PMA Kakul | ISPR Official',
    publishedAt: '2022-01-14T15:00:00Z',
    discoveredAt: '2022-01-14T16:00:00Z',
    author: 'ISPR Official',
    contentType: 'behind-the-scenes',
    thumbnailUrl: '/src/assets/images/drama_sinf_e_aahan_1791045507812.jpg',
    duration: '18:35',
    tags: ['behind-the-scenes', 'sinf-e-aahan', 'ispr', 'pma-kakul', 'military-training'],
    dramaId: 'sinf-e-aahan',
    episodeNumber: null,
    people: ['Dananeer Mobeen', 'Sajal Aly', 'Yumna Zaidi', 'Kubra Khan', 'Ramsha Khan', 'Syra Yousuf'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { producer: 'ISPR & Six Sigma Plus' },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: true
  },
  {
    id: 'cnt-dananeer-vlog-official',
    platform: 'YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=2nF4gK9vB8w',
    embedUrl: 'https://www.youtube.com/embed/2nF4gK9vB8w',
    title: 'A Day On Set With Me — Dananeer Mobeen Official Vlog',
    description: 'Dananeer shares an authentic behind-the-scenes vlog from her official YouTube channel (@DananeerM) giving fans a personal look at wardrobe, scripts, and production routines.',
    caption: 'Welcome to my official YouTube channel! Come spend a chaotic shooting day with me.',
    publishedAt: '2024-05-18T14:00:00Z',
    discoveredAt: '2024-05-18T14:45:00Z',
    author: 'Dananeer Mobeen',
    contentType: 'video',
    thumbnailUrl: '/src/assets/images/dananeer_hero_cinematic_1791045480240.jpg',
    duration: '14:22',
    tags: ['vlog', 'personal', 'official-channel', 'behind-the-scenes'],
    dramaId: null,
    episodeNumber: null,
    people: ['Dananeer Mobeen'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { channelHandle: '@DananeerM', verifiedCreator: true },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: true
  },
  {
    id: 'cnt-zalmi-ambassador-2022',
    platform: 'X',
    sourceUrl: 'https://x.com/PeshawarZalmi/status/1484128919246872580',
    embedUrl: null,
    title: 'Peshawar Zalmi — Official Ambassador Announcement (PSL 7)',
    description: 'Peshawar Zalmi officially announces Dananeer Mobeen as their Youth and Goodwill Brand Ambassador for the Pakistan Super League Season 7.',
    caption: 'Yellow Storm welcomes Dananeer Mobeen as Peshawar Zalmi Youth Ambassador for HBL PSL 7!',
    publishedAt: '2022-01-20T11:00:00Z',
    discoveredAt: '2022-01-20T12:00:00Z',
    author: 'PeshawarZalmi',
    contentType: 'post',
    thumbnailUrl: '/src/assets/images/dananeer_hero_cinematic_1791045480240.jpg',
    duration: null,
    tags: ['peshawar-zalmi', 'psl', 'cricket', 'brand-ambassador'],
    dramaId: null,
    episodeNumber: null,
    people: ['Dananeer Mobeen'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { verifiedAccount: true, sportsFranchise: 'Peshawar Zalmi' },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: false,
    crossPlatformSources: [
      { platform: 'Instagram', url: 'https://www.instagram.com/p/CY9Q4-BqK7k/', note: 'Official Zalmi Jersey reveal photo' }
    ]
  },
  {
    id: 'cnt-dananeer-editorial-shoot',
    platform: 'Instagram',
    sourceUrl: 'https://www.instagram.com/p/CzXm8n2rK5t/',
    embedUrl: null,
    title: 'Couture Editorial Showcase — Festive Haute Series',
    description: 'Verified public fashion photography post highlighting traditional Pakistani craftsmanship and high-fashion styling.',
    caption: 'Gold hues and velvet afternoons. Photography for the festive bridal collection.',
    publishedAt: '2023-11-09T13:15:00Z',
    discoveredAt: '2023-11-09T14:00:00Z',
    author: 'dananeerr',
    contentType: 'photo',
    thumbnailUrl: '/src/assets/images/dananeer_hero_cinematic_1791045480240.jpg',
    duration: null,
    tags: ['photoshoot', 'couture', 'fashion', 'editorial'],
    dramaId: null,
    episodeNumber: null,
    people: ['Dananeer Mobeen'],
    verificationStatus: 'VERIFIED',
    sourceMetadata: { verifiedAccount: true, photographer: 'Maha Photography' },
    lastCheckedAt: '2026-10-03T09:00:00Z',
    sourceAvailable: true,
    embedAvailable: false
  }
];

// Verified chronological career & content timeline
export const SEED_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: 'tl-2021-pawri',
    year: 2021,
    date: '2021-02-06',
    title: 'The "Pawri Hori Hai" Viral Phenomenon',
    subtitle: 'Global Cultural Breakthrough',
    category: 'viral_breakthrough',
    description: 'A spontaneous 5-second video from Nathiagali goes viral globally across Pakistan, India, and the diaspora, transforming Dananeer into an overnight internet sensation and pop culture icon.',
    contentItemId: 'cnt-pawri-orig',
    sourceUrl: 'https://www.instagram.com/p/CLABWqUha8j/',
    platform: 'Instagram',
    verified: true
  },
  {
    id: 'tl-2021-sinf-debut',
    year: 2021,
    date: '2021-11-27',
    title: 'Television Acting Debut in "Sinf-e-Aahan"',
    subtitle: 'Cast as Syeda Sidra in ISPR Mega-Project',
    category: 'drama_debut',
    description: 'Makes her high-profile acting debut alongside top industry stars in Nadeem Baig and Umera Ahmed\'s military drama Sinf-e-Aahan, earning praise for her natural comedic flair and grounded portrayal.',
    contentItemId: 'cnt-sea-bts-ispr',
    sourceUrl: 'https://arydigital.tv/dramas/sinf-e-aahan/',
    platform: 'Broadcast',
    verified: true
  },
  {
    id: 'tl-2022-zalmi',
    year: 2022,
    date: '2022-01-20',
    title: 'Peshawar Zalmi Brand Ambassador',
    subtitle: 'Pakistan Super League (PSL 7)',
    category: 'brand_ambassador',
    description: 'Named official youth and brand ambassador for Peshawar Zalmi in PSL 7, appearing in anthems, fan rallies, and digital youth campaigns.',
    contentItemId: 'cnt-zalmi-ambassador-2022',
    sourceUrl: 'https://x.com/PeshawarZalmi/status/1484128919246872580',
    platform: 'X',
    verified: true
  },
  {
    id: 'tl-2023-mgm-lead',
    year: 2023,
    date: '2023-04-28',
    title: 'First Solo Lead Role in "Muhabbat Gumshuda Meri"',
    subtitle: 'Critical & Commercial Television Triumph',
    category: 'lead_role',
    description: 'Takes center stage as Zobia opposite Khushhal Khan in HUM TV\'s coming-of-age romance, demonstrating powerful dramatic range and cementing her reputation as an A-list dramatic actress.',
    contentItemId: 'cnt-mgm-ost-hum',
    sourceUrl: 'https://www.hum.tv/dramas/muhabbat-gumshuda-meri/',
    platform: 'Broadcast',
    verified: true
  },
  {
    id: 'tl-2023-lsa-win',
    year: 2023,
    date: '2023-10-06',
    title: 'Lux Style Award — Best Emerging Talent',
    subtitle: 'Industry Peer Recognition',
    category: 'award',
    description: 'Wins the prestigious Lux Style Award for Best Emerging Talent in Television, celebrating her transition from digital content creator to recognized television star.',
    contentItemId: 'cnt-lsa-2023-win',
    sourceUrl: 'https://www.youtube.com/watch?v=7uV8hK3PnYq',
    platform: 'Broadcast',
    verified: true
  },
  {
    id: 'tl-2024-very-filmy',
    year: 2024,
    date: '2024-03-12',
    title: 'Lead in Ramadan Special "Very Filmy"',
    subtitle: 'Romantic Comedy Stardom on HUM TV',
    category: 'lead_role',
    description: 'Stars as Sania opposite Ameer Gilani in HUM TV\'s vibrant Ramadan serial, winning audience hearts with sparkling comedic timing and retro-cinema homages.',
    contentItemId: 'cnt-something-haute-2024',
    sourceUrl: 'https://www.hum.tv/dramas/very-filmy/',
    platform: 'Broadcast',
    verified: true
  },
  {
    id: 'tl-2025-2026-archive',
    year: 2025,
    date: '2025-01-15',
    title: 'Digital Expansion & International Brand Campaigns',
    subtitle: 'Global Fashion Collaborations & New Productions',
    category: 'media_appearance',
    description: 'Continues expanding into premium digital content, YouTube episodic vlogs, and top-tier Pakistani fashion week presentations.',
    contentItemId: 'cnt-dananeer-vlog-official',
    sourceUrl: 'https://www.youtube.com/@DananeerM',
    platform: 'YouTube',
    verified: true
  }
];

// Platform configuration status
export const INITIAL_PLATFORM_CONFIGS: PlatformConfig[] = [
  {
    id: 'youtube',
    name: 'YouTube',
    displayName: 'YouTube',
    configured: Boolean(process.env.YOUTUBE_API_KEY),
    status: process.env.YOUTUBE_API_KEY ? 'ACTIVE' : 'NOT_CONFIGURED',
    description: 'Indexes official channel uploads, drama episodes, OSTs, and verified interviews via YouTube Data API v3.',
    requiredEnvVar: 'YOUTUBE_API_KEY',
    itemCount: 4,
    lastSyncAt: new Date().toISOString()
  },
  {
    id: 'instagram',
    name: 'Instagram',
    displayName: 'Instagram',
    configured: Boolean(process.env.INSTAGRAM_ACCESS_TOKEN),
    status: process.env.INSTAGRAM_ACCESS_TOKEN ? 'ACTIVE' : 'NOT_CONFIGURED',
    description: 'Indexes public verified reels, fashion portraits, and official announcements via Instagram Graph API.',
    requiredEnvVar: 'INSTAGRAM_ACCESS_TOKEN',
    itemCount: 2,
    lastSyncAt: new Date().toISOString()
  },
  {
    id: 'x',
    name: 'X',
    displayName: 'X (Twitter)',
    configured: Boolean(process.env.X_BEARER_TOKEN),
    status: process.env.X_BEARER_TOKEN ? 'ACTIVE' : 'NOT_CONFIGURED',
    description: 'Indexes verified brand partnerships, official statements, and media threads via X API v2.',
    requiredEnvVar: 'X_BEARER_TOKEN',
    itemCount: 1,
    lastSyncAt: new Date().toISOString()
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    displayName: 'Snapchat',
    configured: Boolean(process.env.SNAPCHAT_API_KEY),
    status: process.env.SNAPCHAT_API_KEY ? 'ACTIVE' : 'NOT_CONFIGURED',
    description: 'Public Spotlight and story feed discovery integration.',
    requiredEnvVar: 'SNAPCHAT_API_KEY',
    itemCount: 0,
    lastSyncAt: null
  },
  {
    id: 'interview',
    name: 'Interview',
    displayName: 'Interviews & Press',
    configured: true,
    status: 'ACTIVE',
    description: 'Verified print, podcast, and video interview indexers (Something Haute, FUCHSIA, BBC Urdu, Dawn).',
    requiredEnvVar: 'BUILT_IN_SOURCE',
    itemCount: 2,
    lastSyncAt: new Date().toISOString()
  },
  {
    id: 'broadcast',
    name: 'Broadcast',
    displayName: 'Broadcast & Awards',
    configured: true,
    status: 'ACTIVE',
    description: 'Official network broadcasts, Lux Style Awards, and ISPR documentary archives.',
    requiredEnvVar: 'BUILT_IN_SOURCE',
    itemCount: 2,
    lastSyncAt: new Date().toISOString()
  }
];
